image: microsoft/dotnet:1.1-sdk-msbuild

pipelines:
  default:
    - step:
        script:
          - dotnet restore
          - dotnet build
          - dotnet test test/Company.WebApplication1.UnitTests/Company.WebApplication1.UnitTests.csproj
  branches:
    master:
      - step:
          script:
            - dotnet restore
            - dotnet test test/Company.WebApplication1.UnitTests/Company.WebApplication1.UnitTests.csproj
            - dotnet publish src/Company.WebApplication1.Application.MVC/Company.WebApplication1.Application.MVC.csproj -c Release -o $PWD/publish-out

            - bash ./pipeline/deploy-to-azure.sh azurewebapplicationname publish-out
